### ISSUE TITLE
how to disable villagers quests

### ISSUE THREAD

**Issue by unfairDude** [Tonnanto/BasicQuests#10]

**Comment by Tonnanto** [comment]
Go to `plugins/BasicQuests/quest_generation/quest_types.yml` and comment out the `VILLAGER_TRADE` section like so:

`
  - FIND_STRUCTURE:
      weight: 0.2
      value: 480.0

#  - VILLAGER_TRADE:
#      weight: 0.2
#      value: 4.0

  - GAIN_LEVEL:
      weight: 0.1
      value: 2.0

`

Then reload or restart the server. After that no new Villager Quests will be generated. But Villager Quests that where active at the time will still be there. 
You can use `/skip_quest` `/complete_quest` or `/reset_quests` if you want to remove existing Villager Quests.

Hope it helps :)
