### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by Suhkur** [Tonnanto/BasicQuests#4]
Can we somehow turn off that spam?
![image](https://user-images.githubusercontent.com/60276641/178308395-34fd688b-c746-4199-848d-16b5384ca557.png)

**Comment by Tonnanto** [comment]
Not yet unfortunately. The next update will have a solution for this.
I will probably do one of the following:
- Disable progress messages while the scoreboard is open.
- Limit progress messages to 1 message in 10 seconds or something like that.
- The option to turn off progress messages entirely n the config file.
