### ISSUE TITLE
Beetroot quest doesn't work

### ISSUE THREAD

**Issue by Suhkur** [Tonnanto/BasicQuests#6]
When you break beetroot it doesn't count in quest.
Also could you add reload cmd?

**Comment by Tonnanto** [comment]
Thanks for your feedback! I am aware of the issue and am currently working on a fix. v0.3.1 will be published soon.
What exactly do you mean by adding a reload command? A command that updates all existing quests to the current configs?

**Comment by Tonnanto** [comment]
Version 0.3.1 has been published. The issue with harvest quests has been fixed!

**Comment by Suhkur** [comment]
> Thanks for your feedback! I am aware of the issue and am currently working on a fix. v0.3.1 will be published soon. What exactly do you mean by adding a reload command? A command that updates all existing quests to the current configs?

I meant to reload the plugin's config file when I change something there because I don't want to restart the server when I change something constantly.

**Comment by Tonnanto** [comment]
The default spigot `/reload` command can be used to reload the config files. You have to keep in mind though that every configuration related to the generation of new quests only effects newly generated quests. Quests that are currently active wont reflect the config changes. 
You can use `/resetquests` `/completequest` or `/skipquest` to force the generation of new quests.

**Comment by Tonnanto** [comment]
By the way: a reload command is being added in the next update :)
